version: '3.7'

services:
  alvtime-go-client-devcontainer:
    image: alvtime-go-client-devcontainer
    container_name: alvtime-go-client-devcontainer
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - alvtime-go-client-net
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
  dotnet-backend:
    container_name: dotnet-backend
    image: alvtimewebapi_dotnet-backend-no-auth:latest
    links:
      - mssql-db
    environment:
      - ConnectionStrings__AlvTime_db=Data Source=tcp:mssql-db,1433;Initial Catalog=AlvDevDB;User ID=sa;Password=AlvTimeTestErMoro32
    networks:
      - alvtime-go-client-net
    expose:
      - "80"
    ports:
      - "8080:80"
  mssql-db:
    container_name: mssql-db
    image: alvnoas/alvtime-database:latest
    expose:
      - "1433"
    networks:
      - alvtime-go-client-net
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # So that the container doesn't shut down, sleep this thread
        sleep infinity

networks:
  alvtime-go-client-net:
    driver: bridge
    name: alvtime-go-client-net
