name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.GITHUB_ACTOR }}" --password-stdin


    - name: Run tests
      run: |
        docker-compose -f .devcontainer/docker-compose.yaml up -d
        sleep 5
        docker-compose -f .devcontainer/docker-compose.yaml exec alvtime-go-client-devcontainer go test ./...
        docker-compose -f .devcontainer/docker-compose.yaml down
